### ISSUE TITLE
[WS] 데이터 분석에 새로운 기능(산점도 행렬, 실행 결과 저장 블록, 다른 유형 데이터셋 등)을 추가

### ISSUE THREAD

**Issue by Joohee-Moon** [entrylabs/entry-tool#384]
[#5209](https://oss.navercorp.com/entry/entry2/issues/5209)

**Comment by jooheemoon** [comment]
@prisml 

[PR](https://github.com/entrylabs/entry-tool/pull/386) 확인 부탁드립니다.

**Comment by jooheemoon** [comment]
@prisml 

요청 하신, 산점도 행렬 그래프 축 레이블 [PR](https://github.com/entrylabs/entry-tool/pull/387) 확인 부탁드립니다.
