### ISSUE TITLE
entry-tool을 entryjs와 어떻게 같이 사용해야 하나요?

### ISSUE THREAD

**Issue by thoratica** [entrylabs/entry-tool#58]
팝업을 띄울려면 entry-tool이 필요하다는 것 같은데 이걸 entryjs에서 어떻게 해야 불러오나요?

**Comment by kimorkim** [comment]
안녕하세요.
기존에는 entry-tool을 npm으로 배포하였으나, 현재는 entry-tool을 bower를 통하여 번들파일만 배포 하고 있습니다.
사용법은 커멘드에서 아래와 같은 커맨드로 일단 설치가 가능합니다.
```bash
$ bower install entry-tool
```
bower의 사용법은 [공식사이트](https://bower.io/)를 확인해주세요.

bower로 받아진 script파일을 html상에서 로드해서 사용하면됩니다.

entryjs example기준으로는 다음과 같습니다.
```html
<html>
<head>
    <script src="{소스위치}/entry-tool.js"
//...
```

```javascript
import {Dropdown, ColorPicker/* ... 기타 Entry-Tool 컨테이너들 */} from '@entrylabs/tool';
// new Dropdown();
// new ColorPicker();
```
entry-js의 webpack 세팅중 enternals 세팅으로 인해 @entrylabs/tool 이라는 명칭으로 import가 가능합니다.
이외에도 script로드가 되면 ```window.EntryTool``` 로도 같은 객체에 접근 가능합니다.
